import { generateHash, generateAuditId, signReport } from '../utils/crypto.js';
import logger from '../utils/logger.js';

/**
 * Generate a complete audit report
 */
export const generateReport = (contractData, analysisResult) => {
  const auditId = generateAuditId();
  const timestamp = new Date().toISOString();
  const contractHash = generateHash(contractData.code);

  const report = {
    auditId,
    version: '1.0.0',
    timestamp,
    contract: {
      name: contractData.name || 'Unnamed Contract',
      language: contractData.language,
      hash: contractHash,
      codeLength: contractData.code.length,
      version: contractData.version || 'N/A'
    },
    analysis: {
      overallRisk: analysisResult.overallRisk,
      securityScore: analysisResult.securityScore,
      summary: analysisResult.summary,
      analyzedBy: 'ChainGuard AI',
      model: 'Claude Sonnet 4'
    },
    findings: {
      vulnerabilities: analysisResult.vulnerabilities || [],
      bestPractices: analysisResult.bestPractices || [],
      gasOptimization: analysisResult.gasOptimization || [],
      totalIssues: (analysisResult.vulnerabilities || []).length
    },
    recommendations: analysisResult.recommendations || [],
    metadata: {
      generatedBy: 'ChainGuard v1.0.0',
      generatedAt: timestamp,
      engine: 'Claude AI Security Analyzer'
    }
  };

  // Generate signature for the report
  report.signature = signReport(report);

  logger.info(`Audit report generated: ${auditId}`);
  
  return report;
};

/**
 * Generate a summary badge for the contract
 */
export const generateBadge = (securityScore, overallRisk) => {
  let color, label;

  if (securityScore >= 90) {
    color = 'brightgreen';
    label = 'Excellent';
  } else if (securityScore >= 75) {
    color = 'green';
    label = 'Good';
  } else if (securityScore >= 60) {
    color = 'yellow';
    label = 'Fair';
  } else if (securityScore >= 40) {
    color = 'orange';
    label = 'Poor';
  } else {
    color = 'red';
    label = 'Critical';
  }

  return {
    score: securityScore,
    risk: overallRisk,
    color,
    label,
    badgeUrl: `https://img.shields.io/badge/Security-${label}%20(${securityScore})-${color}`
  };
};

/**
 * Format report for markdown display
 */
export const formatMarkdownReport = (report) => {
  const badge = generateBadge(report.analysis.securityScore, report.analysis.overallRisk);
  
  let md = `# Security Audit Report\n\n`;
  md += `![Security Score](${badge.badgeUrl})\n\n`;
  md += `**Audit ID:** ${report.auditId}\n`;
  md += `**Date:** ${new Date(report.timestamp).toLocaleString()}\n`;
  md += `**Contract:** ${report.contract.name}\n`;
  md += `**Security Score:** ${report.analysis.securityScore}/100\n`;
  md += `**Overall Risk:** ${report.analysis.overallRisk}\n\n`;
  
  md += `## Summary\n\n${report.analysis.summary}\n\n`;
  
  if (report.findings.vulnerabilities.length > 0) {
    md += `## Vulnerabilities Found (${report.findings.vulnerabilities.length})\n\n`;
    report.findings.vulnerabilities.forEach((vuln, i) => {
      md += `### ${i + 1}. ${vuln.type} - ${vuln.severity}\n\n`;
      md += `**Description:** ${vuln.description}\n\n`;
      md += `**Location:** ${vuln.location}\n\n`;
      md += `**Recommendation:** ${vuln.recommendation}\n\n`;
    });
  }
  
  if (report.recommendations.length > 0) {
    md += `## Recommendations\n\n`;
    report.recommendations.forEach((rec, i) => {
      md += `${i + 1}. ${rec}\n`;
    });
  }
  
  md += `\n---\n*Generated by ChainGuard AI Security Analyzer*\n`;
  
  return md;
};

export default {
  generateReport,
  generateBadge,
  formatMarkdownReport
};